### ISSUE TITLE
dw icon [name] [material]  Not working in 1.20.4

### ISSUE THREAD

**Issue by nunavailabul** [eccentricdevotion/DiscoverWarps#6]
/dw icon [name] [material]  Doesn't appear to do anything and My warp list is just pressure plates since updating to 1.20.4
Paper 1.20.4
DW 1.7.1

**Comment by eccentricdevotion** [comment]
Looks like some Bukkit materials ie ones that only have a block form won't work e.g. CYAN_CANDLE_CAKE - try using something else for the icon.
I've reduced the tab completion list for the command in the lastest update - get it from here:
http://tardisjenkins.duckdns.org:8080/job/DiscoverWarps/
